set -g base-index 1
set -g default-terminal "tmux-256color"
set -g escape-time 1
set -g history-limit 1024
set -g message-style bg=colour3,fg=colour0
set -g mode-keys vi
set -g mode-style bg=colour3,fg=colour0
set -g mouse on
set -g pane-active-border-style fg=colour4
set -g pane-base-index 1
set -g pane-border-format "#[fg=colour7] #{pane_index} #{?@pane_name,#{@pane_name},#{pane_current_command}} "
set -g pane-border-lines single
set -g pane-border-status top
set -g pane-border-style fg=colour8
set -g prefix `
set -g status on
set -g status-bg colour0
set -g status-fg colour7
set -g status-left "#[fg=colour4]λ "
set -g status-right "#[fg=colour1](#S)"
set -g window-status-current-format "#[bg=colour8,nounderscore] #W "
set -g window-status-format " #W "
set -g window-status-separator ""

bind-key R source-file ~/.tmux.conf
bind-key ` send-prefix
bind-key b set -g status
bind-key e command-prompt -I "#{@pane_name}" -p "name" { set-option -p @pane_name "%%" }
bind-key m set -g mouse
bind-key '{' swap-pane -U
bind-key '}' swap-pane -D
