"ui.background" = { bg = "black" }
"ui.background.separator" = { fg = "red" }
"ui.cursor" = { modifiers = ["reversed"] }
"ui.cursor.match" = { fg = "yellow", underline = { color = "yellow", style = "line" } }
"ui.cursor.primary" = { modifiers = ["reversed", "slow_blink"] }
"ui.cursor.secondary" = { modifiers = ["reversed"] }
"ui.cursorcolumn.primary" = { bg = "gray" }
"ui.cursorcolumn.secondary" = { bg = "gray" }
"ui.cursorline.primary" = { underline = { color = "gray", style = "line" } }
"ui.cursorline.secondary" = { underline = { color = "gray", style = "line" } }
"ui.gutter" = "gray"
"ui.help" = { fg = "gray" }
"ui.linenr" = { fg = "gray" }
"ui.linenr.selected" = { fg = "white",  modifiers = ["bold"] }
"ui.menu" = { fg = "white" }
"ui.menu.scroll" = { fg = "gray" }
"ui.menu.selected" = { bg = "gray" }
"ui.popup" = { fg = "white", bg = "gray" }
"ui.selection" = { bg = "gray" }
"ui.statusline" = { fg = "green", bg = "gray" }
"ui.statusline.inactive" = { fg = "yellow", bg = "gray" }
"ui.statusline.insert" = { fg = "black", bg = "green" }
"ui.statusline.normal" = { fg = "black", bg = "blue" }
"ui.statusline.select" = { fg = "black", bg = "magenta" }
"ui.text" = { fg = "white" }
"ui.text.focus" = { fg = "white", bg = "gray" }
"ui.virtual.indent-guide" = "gray"
"ui.virtual.inlay-hint" = { fg = "white", bg = "gray" }
"ui.virtual.inlay-hint.parameter" = { fg = "white", bg = "gray"}
"ui.virtual.inlay-hint.type" = { fg = "white", bg = "gray"}
"ui.virtual.jump-label" = { fg = "blue", modifiers = ["bold", "underlined"] }
"ui.virtual.ruler" = { bg = "gray" }
"ui.virtual.whitespace" = "gray"
"ui.virtual.wrap" = "gray"
"ui.window" = { fg = "gray" }

"info" = "blue"
"hint" = "gray"
"debug" = "gray"
"warning" = "yellow"
"error" = "red"

"diagnostic.debug" = { underline ={ color ="gray", style = "dashed" } }
"diagnostic.error" = { underline = { color ="red", style = "curl" } }
"diagnostic.hint" = { underline = { color = "gray", style = "double_line" } }
"diagnostic.info" = { underline = { color = "blue", style = "dotted" } }
"diagnostic.warning" = { underline = { color = "yellow", style = "curl" } }

"attribute" = "yellow"
"comment" = "gray"
"constant" = "yellow"
"constant.character.escape" = "cyan"
"constant.numeric" = "yellow"
"constructor" = "blue"
"function" = "blue"
"keyword" = "magenta"
"label" = "magenta"
"namespace" = "magenta"
"special" = "blue"
"string"  = "green"
"type" = "yellow"
"variable" = "red"
"variable.other.member" = "green"

"diff.delta" = "blue"
"diff.delta.moved" = "blue"
"diff.minus" = "red"
"diff.plus" = "green"

"markup.bold" = { fg = "yellow", modifiers = ["bold"] }
"markup.heading" = "blue"
"markup.insert" = { fg = "green" }
"markup.italic" = { fg = "magenta", modifiers = ["italic"] }
"markup.link.text" = "red"
"markup.link.url" = { fg = "yellow", underline = { color = "yellow", style = "line"} }
"markup.list" = "red"
"markup.normal" = { fg = "blue" }
"markup.quote" = "cyan"
"markup.raw" = "green"
"markup.select" = { fg = "magenta" }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
