#!/usr/bin/env dash

alt + Tab
	bspc desktop -f last

alt + {h,k,j,l}
	bspc node -v {-20 0,0 -20,0 20,20 0}

ctrl + Tab
	bspc node -f last

ctrl + alt + {Left,Right}
	bspc desktop -f {prev,next}.local

super + {_, shift +} {1-9}
	bspc {desktop -f,node -d} ^{1-9}

super + {_,shift +} {Left,Up,Down,Right}
	bspc node -{f,s} {west,north,south,east}

super + {h,j,k,l}
	bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}

super + shift + {h,j,k,l}
	bspc node -z {right -20 0,top 0 20,bottom 0 -20,left 20 0}

super + d
	bspc node -t floating

super + e
	9 spawn st vifm

super + f
	bspc desktop -l next

super + m
	bspc node -s biggest.local

super + p
	dmenu_run

super + q
	bspc node -{c,k}

super + shift + q
	(pkill -f bar & pfill -f sxhkd & bspc quit)

super + r
	bspc wm -r

super + Return
	spawn st

super + s
	bspc node -s last

super + t
	bspc node -t tiled

super + z
	switch
