#!/usr/bin/env dash

pgrep -x sxhkd >/dev/null || sxhkd &

xsetroot -cursor_name left_ptr

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config automatic_scheme spiral
bspc config border_width 2
bspc config borderless_monocle true
bspc config focus_follows_pointer true
bspc config gapless_monocle true
bspc config pointer_modifier mod1
bspc config split_ratio 0.5
bspc config window_gap 4
