#!/usr/bin/env bash

xsetroot -cursor_name left_ptr
sxhkd &
 
bspc config border_width 2
bspc config window_gap 1
 
bspc config split_ratio 0.62
bspc config focus_follows_pointer true
bspc config pointer_modifier mod1
 
bspc config automatic_scheme spiral
