[font]
size = 12.0

[font.normal]
family = "Consolas"
style = "Regular"

[cursor]
style = "Beam"
thickness = 0.2

[colors.primary]
background = "#121212"
foreground = "#f8f8f2"

[colors.cursor]
text = "#121212"
cursor = "#f8f8f2"

[colors.normal]
black = "#121212"
red = "#ff614d"
green = "#50c878"
yellow = "#e6db74"
blue = "#128bd5"
magenta = "#fd3f92"
cyan = "#64ffda"
white = "#f8f8f2"

[colors.bright]
black = "#262626"
red = "#ff614d"
green = "#50c878"
yellow = "#e6db74"
blue = "#128bd5"
magenta = "#fd3f92"
cyan = "#64ffda"
white = "#f8f8f2"

[keyboard]
bindings = [
  { key = "F11", action = "ToggleFullscreen" }
]

[selection]
save_to_clipboard = true
