theme = "terminal"

[editor]
gutters = ["diagnostics", "spacer", "diff"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
X = ["extend_line_up", "extend_to_line_bounds"]
A-x = "extend_to_line_bounds"

[keys.normal.space]
z = [":pipe tgpt -c -q"]

[keys.select]
X = ["extend_line_up", "extend_to_line_bounds"]
A-x = "extend_to_line_bounds"
